ci: 🐛 Updated preview.yml

diff --git a/.github/workflows/preview.yml b/.github/workflows/preview.yml
--- a/.github/workflows/preview.yml
+++ b/.github/workflows/preview.yml
@@ -128,6 +128,26 @@ jobs:
       - name: Verify .vercel/.env.preview.local Content
         run: cat .vercel/.env.preview.local
 
+      - name: Remove Existing Vercel Environment Variables (if any)
+        run: |
+          vercel env ls | grep AWS_REGION && vercel env rm AWS_REGION preview --yes || echo "AWS_REGION not found"
+          vercel env ls | grep AWS_ACCESS_KEY_ID && vercel env rm AWS_ACCESS_KEY_ID preview --yes || echo "AWS_ACCESS_KEY_ID not found"
+          vercel env ls | grep AWS_SECRET_ACCESS_KEY && vercel env rm AWS_SECRET_ACCESS_KEY preview --yes || echo "AWS_SECRET_ACCESS_KEY not found"
+          vercel env ls | grep AUTH_GITHUB_ID && vercel env rm AUTH_GITHUB_ID preview --yes || echo "AUTH_GITHUB_ID not found"
+          vercel env ls | grep AUTH_GITHUB_SECRET && vercel env rm AUTH_GITHUB_SECRET preview --yes || echo "AUTH_GITHUB_SECRET not found"
+          vercel env ls | grep AUTH_SECRET && vercel env rm AUTH_SECRET preview --yes || echo "AUTH_SECRET not found"
+          vercel env ls | grep AWS_TABLE_NAME && vercel env rm AWS_TABLE_NAME preview --yes || echo "AWS_TABLE_NAME not found"
+
+      - name: Set Vercel Env Variable
+        run: |
+          echo "AWS_REGION=${{ vars.AWS_REGION }}" | vercel env add AWS_REGION preview
+          echo "ZNAP_AWS_SECRET_ACCESS_KEY=$ZNAP_AWS_SECRET_ACCESS_KEY" | vercel env add AWS_ACCESS_KEY_ID
+          echo "ZNAP_AWS_SECRET_ACCESS_KEY=$ZNAP_AWS_SECRET_ACCESS_KEY" | vercel env add AWS_SECRET_ACCESS_KEY
+          echo "AUTH_GITHUB_ID=${{ secrets.AUTH_GITHUB_ID }}" | vercel env add AUTH_GITHUB_ID
+          echo "AUTH_GITHUB_SECRET=${{ secrets.AUTH_GITHUB_SECRET }}" | vercel env add AUTH_GITHUB_SECRET
+          echo "AUTH_SECRET=${{ secrets.AUTH_SECRET }}" | vercel env add AUTH_SECRET
+          echo "${{ vars.AWS_TABLE_NAME }}" | vercel env add AWS_TABLE_NAME
+
       - name: Build project artifacts
 
         run: |
